const FEATURED_PLAYLISTS = [
  {
    id: 'featured-top-brasil',
    name: 'Top Brasil',
    cover: 'src/imagens/top-brasil.png',
    isFeatured: true,
    tracks: [
      { name: 'Jetski', artists: [{ name: 'Pedro Sampaio' }, { name: 'MC Meno K' }, { name: 'Melody' }] },
      { name: 'Pela Última Vez (Ao Vivo)', artists: [{ name: 'Grupo Menos É Mais' }, { name: 'Nattan' }] },
      { name: 'Eu Vou Na Sua Casa', artists: [{ name: 'Felipe Amorim' }, { name: 'Vitão' }, { name: 'Bin' }, { name: 'Malibu' }] },
      { name: 'Ama Um Maloqueiro', artists: [{ name: 'Rafa e Junior' }, { name: 'Hugo & Guilherme' }, { name: 'DJ Ari SL' }] },
      { name: 'Eu Me Apaixonei', artists: [{ name: 'Vitinho Imperador' }] },
      { name: 'Posso Até Não Te Dar Flores', artists: [{ name: 'DJ Japa NK' }, { name: 'MC Meno K' }, { name: 'MC Ryan SP' }, { name: 'MC Jacaré' }] },
      { name: 'Se Eu Te Perdoar (Ao Vivo)', artists: [{ name: 'Clayton & Romário' }, { name: 'Zé Felipe' }] },
      { name: 'Sequência Feiticeira', artists: [{ name: 'Pedro Sampaio' }, { name: 'MC GW' }, { name: 'MC Jhey' }, { name: 'MC Rodrigo do CN' }, { name: 'MC Nito' }] },
      { name: 'Um Dia Te Levo Comigo', artists: [{ name: 'Israel & Rodolffo' }] },
      { name: 'Desliza (Ólhinho no Corpinho)', artists: [{ name: 'Léo Santana' }, { name: 'Melody' }] },
      { name: 'Deixa Eu (Ao Vivo)', artists: [{ name: 'Murilo Huff' }] },
      { name: 'Eu Só Quero Você', artists: [{ name: 'AgroPlay' }, { name: 'Ana Castela' }, { name: 'Zé Felipe' }] },
      { name: 'Desocupa', artists: [{ name: 'Matheus Vargas' }, { name: 'Cleber & Cauan' }] },
      { name: 'Ilusão de Ótica (Ao Vivo)', artists: [{ name: 'Matheus & Kauan' }, { name: 'Ana Castela' }] },
      { name: 'Na Imaginação', artists: [{ name: 'Eric Land' }, { name: 'MC Livinho' }, { name: 'DJ Topo' }] },
      { name: 'Baqueado (Ao Vivo)', artists: [{ name: 'Panda' }, { name: 'Ícaro e Gilmar' }, { name: 'MJ Records' }] },
      { name: 'Orçamento (Ao Vivo)', artists: [{ name: 'Luan Pereira' }, { name: 'Ana Castela' }] },
      { name: 'P do Pecado (Ao Vivo)', artists: [{ name: 'Grupo Menos É Mais' }, { name: 'Simone Mendes' }] },
      { name: 'Cópia Proibida', artists: [{ name: 'Léo Foguete' }] },
      { name: 'Tubarões (Ao Vivo)', artists: [{ name: 'Diego & Victor Hugo' }] },
      { name: 'Ninguém Pode Saber', artists: [{ name: 'CountryBeat' }, { name: 'Ana Castela' }] },
      { name: 'Saudade do Carai', artists: [{ name: 'Mari Fernandez' }, { name: 'Grelo' }, { name: 'Natanzinho Lima' }] },
      { name: 'Me Postou no Daily - Festa do Big G', artists: [{ name: 'MC GP' }, { name: 'MC Lele JP' }, { name: 'DJ Davi Dogdog' }, { name: 'DJ Andrabeat' }] },
      { name: 'Grau de Maluca (Ao Vivo)', artists: [{ name: 'Guilherme & Benuto' }, { name: 'Grupo Menos É Mais' }, { name: 'Matheus Fernandes' }] },
      { name: 'Mudar Pra Lua (Ao Vivo)', artists: [{ name: 'Guilherme & Benuto' }, { name: 'Xand Avião' }] },
      { name: 'Vitamina C (Ao Vivo)', artists: [{ name: 'Suel' }, { name: 'Grupo Menos É Mais' }] },
      { name: 'Todo Mundo Menos Eu (Ao Vivo)', artists: [{ name: 'Hugo & Guilherme' }, { name: 'Ana Castela' }] },
      { name: 'Gostosin', artists: [{ name: 'Anitta' }, { name: 'Felipe Amorim' }, { name: 'Hitmaker' }] },
      { name: 'Apaga Apaga Apaga (Ao Vivo)', artists: [{ name: 'Danilo e Davi' }] },
      { name: 'Vai Cair Água (Ao Vivo)', artists: [{ name: 'Diego & Arnaldo' }, { name: 'Zé Neto & Cristiano' }] },
      { name: 'De Tanto Te Querer', artists: [{ name: 'Maiara & Maraisa' }] },
      { name: 'Sonho de Amor (Ao Vivo)', artists: [{ name: 'Natanzinho Lima' }] },
      { name: 'Fama de Ruim (Ao Vivo)', artists: [{ name: 'Lauana Prado' }] },
      { name: 'Apaguei Pra Todos (Ao Vivo)', artists: [{ name: 'Ferrugem' }, { name: 'Sorriso Maroto' }] },
      { name: 'Alô Virgínia (Ao Vivo)', artists: [{ name: 'Grupo Chocolate' }, { name: 'Turma do Pagode' }] },
      { name: 'Vacilona (Ao Vivo)', artists: [{ name: 'Kaique e Felipe' }, { name: 'Luan Pereira' }] },
      { name: 'Saudade Proibida (Ao Vivo)', artists: [{ name: 'Simone Mendes' }] },
      { name: 'Última Noite (Solo)', artists: [{ name: 'Léo Foguete' }] },
      { name: 'Coração Partido (Corazón Partío) (Ao Vivo)', artists: [{ name: 'Grupo Menos É Mais' }] },
      { name: 'Ignora (Ao Vivo)', artists: [{ name: 'Felipe e Rodrigo' }] },
      { name: 'Encosta na Parede', artists: [{ name: 'MC Pedrinho' }, { name: 'Teko Bolado' }, { name: 'Rizzi Get Busy' }, { name: 'Tropa da W&S' }] },
      { name: 'Talvez Você Precise de Mim', artists: [{ name: 'Supernova Ent' }, { name: 'Veigh' }] },
      { name: 'Descer', artists: [{ name: 'Kew' }, { name: 'DJ LK da Escócia' }] },
      { name: 'Em Busca da Minha Sorte (Ao Vivo)', artists: [{ name: 'Thiaguinho' }] },
      { name: 'Vagabundo', artists: [{ name: 'Gusttavo Lima' }, { name: 'Luis Fonsi' }] },
      { name: 'Amor Bandido', artists: [{ name: 'J. Eskine' }, { name: 'Alef Donk' }, { name: 'Oruam' }] },
      { name: "Sua Boca Mente (You're Still The One)", artists: [{ name: 'Zé Felipe' }, { name: 'Ana Castela' }] },
      { name: 'Nunca Mais', artists: [{ name: 'MC Daniel' }, { name: 'Gloria Groove' }] },
      { name: 'Olha Onde Eu Tô', artists: [{ name: 'Ana Castela' }] },
      { name: 'Fica Com Deus (Ao Vivo)', artists: [{ name: 'Yan' }, { name: 'Sorriso Maroto' }] },
      { name: 'Melzinho', artists: [{ name: 'Talita Mel' }, { name: 'Xand Avião' }] },
      { name: 'Amor Traumatizado', artists: [{ name: 'Felipe Amorim' }, { name: 'Carol Biazin' }] },
      { name: 'Resumindo (Ao Vivo)', artists: [{ name: 'Zé Neto & Cristiano' }] },
      { name: 'Caos de Alguém (Ao Vivo)', artists: [{ name: 'Felipe e Rodrigo' }] },
      { name: 'Tudo Fica Blue', artists: [{ name: 'Grupo Menos É Mais' }] },
      { name: 'O Que É Que o Cowboy Gosta', artists: [{ name: 'CountryBeat' }] },
      { name: 'Dona (Ao Vivo)', artists: [{ name: 'Luan Santana' }, { name: 'Léo Foguete' }] },
      { name: 'Escondendo o Ouro (Ao Vivo)', artists: [{ name: 'Zé Neto & Cristiano' }] },
      { name: 'Amigo da Minha Saudade (Ao Vivo)', artists: [{ name: 'Henrique & Juliano' }] },
      { name: 'Querendo Te Amar (Ao Vivo)', artists: [{ name: 'Gustavo Mioto' }] }
    ]
  },
  {
    id: 'featured-sertanejo',
    name: 'Sertanejo',
    cover: 'src/imagens/Sertanejo.png',
    isFeatured: true,
    tracks: [
      { name: 'Ainda Lembro', artists: [{ name: 'Marília Mendonça' }] },
      { name: 'Atrasadinha', artists: [{ name: 'Felipe Araújo' }, { name: 'Ferrugem' }] },
      { name: 'Largado às Traças', artists: [{ name: 'Zé Neto & Cristiano' }] },
      { name: 'Notificação Preferida', artists: [{ name: 'Zé Neto & Cristiano' }] },
      { name: 'Bebi Liguei', artists: [{ name: 'Marília Mendonça' }] },
      { name: 'Infiel', artists: [{ name: 'Marília Mendonça' }] },
      { name: 'Medo Bobo', artists: [{ name: 'Maiara & Maraisa' }] },
      { name: 'Amor da Sua Cama', artists: [{ name: 'Jorge & Mateus' }] },
      { name: 'Propaganda', artists: [{ name: 'Jorge & Mateus' }] },
      { name: 'Coração Cachorro', artists: [{ name: 'Ávine Vinny' }, { name: 'Matheus Fernandes' }] },
      { name: 'Batom de Cereja', artists: [{ name: 'Israel & Rodolffo' }] }
    ]
  },
  {
    id: 'featured-funk',
    name: 'Funk Brasil',
    cover: 'src/imagens/Funk Brasil.png',
    isFeatured: true,
    tracks: [
      { name: 'Vai Embrazando', artists: [{ name: 'MC Zaac' }, { name: 'MC Vigary' }] },
      { name: 'Bum Bum Tam Tam', artists: [{ name: 'MC Fioti' }] },
      { name: 'Envolvimento', artists: [{ name: 'MC Loma' }] },
      { name: 'Rave de Favela', artists: [{ name: 'MC Lan' }, { name: 'Major Lazer' }] },
      { name: 'Tá Tranquilo Tá Favorável', artists: [{ name: 'MC Bin Laden' }] },
      { name: 'Baile de Favela', artists: [{ name: 'MC João' }] },
      { name: 'Deu Onda', artists: [{ name: 'MC G15' }] },
      { name: 'Ela é do Tipo', artists: [{ name: 'MC Kevin o Chris' }] },
      { name: 'Só Quer Vrau', artists: [{ name: 'MC MM' }] },
      { name: 'Medley da Gaiola', artists: [{ name: 'MC Kevin o Chris' }] },
      { name: 'Tudo Ok', artists: [{ name: 'Thiaguinho MT' }, { name: 'Mila' }] },
      { name: 'Sentadão', artists: [{ name: 'Pedro Sampaio' }, { name: 'Felipe Original' }] }
    ]
  },
  {
    id: 'featured-rock-brasil',
    name: 'Rock Brasil',
    cover: 'src/imagens/Rock Brasil.png',
    isFeatured: true,
    tracks: [
      { name: 'Pais e Filhos', artists: [{ name: 'Legião Urbana' }] },
      { name: 'Tempo Perdido', artists: [{ name: 'Legião Urbana' }] },
      { name: 'Eduardo e Mônica', artists: [{ name: 'Legião Urbana' }] },
      { name: 'Ainda é Cedo', artists: [{ name: 'Legião Urbana' }] },
      { name: 'Eu Nasci Há Dez Mil Anos Atrás', artists: [{ name: 'Raul Seixas' }] },
      { name: 'Maluco Beleza', artists: [{ name: 'Raul Seixas' }] },
      { name: 'Gita', artists: [{ name: 'Raul Seixas' }] },
      { name: 'Dois Rios', artists: [{ name: 'Skank' }] },
      { name: 'Vou Deixar', artists: [{ name: 'Skank' }] },
      { name: 'Anna Júlia', artists: [{ name: 'Los Hermanos' }] },
      { name: 'Primeiros Erros', artists: [{ name: 'Capital Inicial' }] },
      { name: 'Música Urbana', artists: [{ name: 'Capital Inicial' }] }
    ]
  },
  {
    id: 'featured-mpb',
    name: 'MPB',
    cover: 'src/imagens/mpb.png',
    isFeatured: true,
    tracks: [
      { name: 'Garota de Ipanema', artists: [{ name: 'Tom Jobim' }, { name: 'Vinícius de Moraes' }] },
      { name: 'Águas de Março', artists: [{ name: 'Tom Jobim' }] },
      { name: 'Construção', artists: [{ name: 'Chico Buarque' }] },
      { name: 'O Que Será', artists: [{ name: 'Chico Buarque' }] },
      { name: 'Sampa', artists: [{ name: 'Caetano Veloso' }] },
      { name: 'Sozinho', artists: [{ name: 'Caetano Veloso' }] },
      { name: 'Como Nossos Pais', artists: [{ name: 'Elis Regina' }] },
      { name: 'O Bêbado e a Equilibrista', artists: [{ name: 'Elis Regina' }] },
      { name: 'Anunciação', artists: [{ name: 'Alceu Valença' }] },
      { name: 'Tropicana', artists: [{ name: 'Alceu Valença' }] },
      { name: 'Amor I Love You', artists: [{ name: 'Marisa Monte' }] },
      { name: 'Ainda Lembro', artists: [{ name: 'Marisa Monte' }] }
    ]
  },
  {
    id: 'featured-pop-internacional',
    name: 'Pop Internacional',
    cover: 'src/imagens/pop-internacional.png',
    isFeatured: true,
    tracks: [
      { name: 'Blinding Lights', artists: [{ name: 'The Weeknd' }] },
      { name: 'Flowers', artists: [{ name: 'Miley Cyrus' }] },
      { name: 'Anti-Hero', artists: [{ name: 'Taylor Swift' }] },
      { name: 'As It Was', artists: [{ name: 'Harry Styles' }] },
      { name: 'Unholy', artists: [{ name: 'Sam Smith' }, { name: 'Kim Petras' }] },
      { name: 'Bad Habit', artists: [{ name: 'Steve Lacy' }] },
      { name: 'About Damn Time', artists: [{ name: 'Lizzo' }] },
      { name: 'Heat Waves', artists: [{ name: 'Glass Animals' }] },
      { name: 'Stay', artists: [{ name: 'The Kid LAROI' }, { name: 'Justin Bieber' }] },
      { name: 'Levitating', artists: [{ name: 'Dua Lipa' }] },
      { name: 'Peaches', artists: [{ name: 'Justin Bieber' }] },
      { name: 'drivers license', artists: [{ name: 'Olivia Rodrigo' }] }
    ]
  },
  {
    id: 'featured-treino',
    name: 'Treino Pesado',
    cover: 'src/imagens/treino.png',
    isFeatured: true,
    tracks: [
      { name: 'Lose Yourself', artists: [{ name: 'Eminem' }] },
      { name: 'Till I Collapse', artists: [{ name: 'Eminem' }, { name: 'Nate Dogg' }] },
      { name: 'Stronger', artists: [{ name: 'Kanye West' }] },
      { name: 'Eye of the Tiger', artists: [{ name: 'Survivor' }] },
      { name: "Can't Hold Us", artists: [{ name: 'Macklemore' }, { name: 'Ryan Lewis' }] },
      { name: 'Remember The Name', artists: [{ name: 'Fort Minor' }] },
      { name: 'Thunderstruck', artists: [{ name: 'AC/DC' }] },
      { name: 'Enter Sandman', artists: [{ name: 'Metallica' }] },
      { name: 'Pump It', artists: [{ name: 'Black Eyed Peas' }] },
      { name: 'Levels', artists: [{ name: 'Avicii' }] },
      { name: 'Titanium', artists: [{ name: 'David Guetta' }, { name: 'Sia' }] },
      { name: "Don't Stop Me Now", artists: [{ name: 'Queen' }] }
    ]
  },
  {
    id: 'featured-pagode',
    name: 'Pagode',
    cover: 'src/imagens/pagode.png',
    isFeatured: true,
    tracks: [
      { name: 'Deixa Acontecer', artists: [{ name: 'Grupo Revelação' }] },
      { name: 'Tá Vendo Aquela Lua', artists: [{ name: 'Exaltasamba' }] },
      { name: 'Telegrama', artists: [{ name: 'Zeca Pagodinho' }] },
      { name: 'Verdade', artists: [{ name: 'Zeca Pagodinho' }] },
      { name: 'Deixa Eu Te Amar', artists: [{ name: 'Sorriso Maroto' }] },
      { name: 'Assim Você Mata o Papai', artists: [{ name: 'Sorriso Maroto' }] },
      { name: 'Temporal', artists: [{ name: 'Thiaguinho' }] },
      { name: 'Ousadia & Alegria', artists: [{ name: 'Thiaguinho' }] },
      { name: 'Sou Assim Sem Você', artists: [{ name: 'Claudinho & Buchecha' }] },
      { name: 'Só Love', artists: [{ name: 'Exaltasamba' }] },
      { name: 'Meu Lugar', artists: [{ name: 'Arlindo Cruz' }] },
      { name: 'O Show Tem Que Continuar', artists: [{ name: 'Arlindo Cruz' }] }
    ]
  }
];

const SPECIAL_PLAYLISTS = [
  /*
  {
    id: 'special-louvores-agitados-2026',
    name: 'Louvores Agitados 2026 🙌🔥 | Gospel Animado & Hinos de Celebração',
    cover: 'src/imagens/louvores-agitados-2026.jpeg',
    isSpecial: true,
    tracks: [
      { name: 'Moisés / Cântico a Moisés (Ao Vivo)', artists: [{ name: 'Fernandinho' }] },
      { name: 'Galileu (Ao Vivo)', artists: [{ name: 'Fernandinho' }] },
      { name: 'Sua Justiça Prevalecerá (Ao Vivo)', artists: [{ name: 'Nívea Soares' }] },
      { name: 'Pedra na Mão (Ao Vivo)', artists: [{ name: 'Discopraise' }] },
      { name: '1000 Graus (Live)', artists: [{ name: 'Renascer Praise' }] },
      { name: 'Efésios 6', artists: [{ name: 'Anderson Freire' }] },
      { name: 'Daniel (feat. Fernandinho)', artists: [{ name: 'Thalles Roberto' }] },
      { name: 'Escudo', artists: [{ name: 'DJ PV' }] },
      { name: 'Seu Sangue (Ao Vivo)', artists: [{ name: 'Fernandinho' }] },
      { name: 'Filho do Deus Vivo (Ao Vivo)', artists: [{ name: 'Nívea Soares' }] },
      { name: 'Festa de Crente (Ao Vivo)', artists: [{ name: 'Banda Som e Louvor' }] },
      { name: 'Teu Amor Não Falha (Ao Vivo)', artists: [{ name: 'Nívea Soares' }] },
      { name: 'Louve (Ao Vivo)', artists: [{ name: 'Lukas Agustinho' }] },
      { name: 'Algo Novo Vindo', artists: [{ name: 'Get Worship' }] },
      { name: '500 Graus (Ao Vivo)', artists: [{ name: 'Thalles Roberto' }] },
      { name: 'Jesus Me Conquistou', artists: [{ name: 'Ton Carfi' }] },
      { name: 'Festa dos Crentes', artists: [{ name: 'Ton Carfi' }] },
      { name: 'Verdade (Ao Vivo)', artists: [{ name: 'Leonardo Gonçalves' }] },
      { name: 'Lindo Momento (Remix)', artists: [{ name: 'DJ PV' }] },
      { name: 'Só o Começo (Remix)', artists: [{ name: 'Gui Brazil' }] },
      { name: 'É Tudo Sobre Você (Remix)', artists: [{ name: 'Morada' }] },
      { name: 'Bondade de Deus (Remix)', artists: [{ name: 'DJ PV' }] },
      { name: 'Vem Incendiar Meu Coração (Remix)', artists: [{ name: 'Gui Brazil' }] },
      { name: 'Adrenalina', artists: [{ name: 'Duo Franco' }] },
      { name: 'Crente Menino (Ao Vivo)', artists: [{ name: 'Ministério Ardendo em Fogo' }] },
      { name: 'Arde Outra Vez', artists: [{ name: 'Thalles Roberto' }] },
      { name: 'Rei Davi', artists: [{ name: 'DJ PV' }] },
      { name: 'Desperta (Wake)', artists: [{ name: 'Gabriela Rocha' }] },
      { name: 'Vitória no Deserto', artists: [{ name: 'Aline Barros' }] },
      { name: 'Estamos de Pé (Ao Vivo)', artists: [{ name: 'Marcus Salles' }] },
      { name: 'Levanto um Aleluia (Ao Vivo)', artists: [{ name: 'Diante do Trono' }] },
      { name: 'Que Ruja o Leão (Remix)', artists: [{ name: 'DJ Vitor Capoia' }] },
      { name: 'Chuva de Bênçãos (Ao Vivo)', artists: [{ name: 'Fernandinho' }] },
      { name: 'Eu Sou Teu (Rooftops) (Ao Vivo)', artists: [{ name: 'Gabriela Rocha' }] },
      { name: 'Nosso Deus (Our God)', artists: [{ name: 'Gui Rebustini' }] },
      { name: 'Abra os Olhos do Meu Coração', artists: [{ name: 'David Quinlan' }] },
      { name: 'Nada é Impossível', artists: [{ name: 'Quatro por Um' }] },
      { name: 'A Tua Graça Me Basta', artists: [{ name: 'Quatro por Um' }] },
      { name: 'Diante de Ti', artists: [{ name: 'Quatro por Um' }] },
      { name: 'Graça', artists: [{ name: 'Eli Soares' }] },
      { name: 'Te Agradeço', artists: [{ name: 'Kleber Lucas' }] },
      { name: 'Emanuel (Ao Vivo)', artists: [{ name: 'Fernandinho' }] },
      { name: 'Hey, Pai (Ao Vivo)', artists: [{ name: 'Isadora Pompeo' }] },
      { name: 'Meu Salvador', artists: [{ name: 'Gabriela Rocha' }] },
      { name: 'Por Amor (Ao Vivo)', artists: [{ name: 'Adoração Central' }] },
      { name: 'Favor de Deus (Ao Vivo)', artists: [{ name: 'Discopraise' }] }
    ]
  },
  */
  {
    id: 'special-funk-bruxaria-2026',
    name: 'FUNK BRUXARIA ATUALIZADO 2026 | Automotivo • Submundo • Beat Agressivo • Mandelão',
    cover: 'src/imagens/FUNK BRUXARIA ATUALIZADO | Automotivo | Submundo | Beat Agressivo | Mandelão | Passinho.png',
    isSpecial: true,
    tracks: [
      { name: 'Ela é Profissional', artists: [{ name: 'GP da ZL' }] },
      { name: 'Sobe na Moto Roubadona', artists: [{ name: 'DJ Kelvinho da ZS' }] },
      { name: '2026', artists: [{ name: 'Jhow' }] },
      { name: 'Só Essencial', artists: [{ name: '4Kbatu' }] },
      { name: 'Tô na Brasília com o Zigão', artists: [{ name: 'DJ Zigão' }] },
      { name: 'Ritmo Lilly Wood', artists: [{ name: 'DJ MTN' }] },
      { name: 'FE!N Mandelão', artists: [{ name: 'DJ Blakes' }] },
      { name: 'Ela da Palinha', artists: [{ name: 'DJ Guilherme Borges' }] },
      { name: 'HY BYD', artists: [{ name: 'Zago' }] },
      { name: 'Bruxaria Automotiva Bye Bye', artists: [{ name: 'MC K.K' }] },
      { name: 'Introdução em Dó Menor', artists: [{ name: 'GP da ZL' }] },
      { name: 'Proposta Indecente', artists: [{ name: 'Gui 07' }] },
      { name: 'Sacode Automotivo', artists: [{ name: 'DJ Bruninho 17' }] },
      { name: 'Montagem Sarra Sarra', artists: [{ name: 'DJ Yuzak' }] },
      { name: 'Acelerada', artists: [{ name: 'sma$her' }] },
      { name: 'Submundo Bailão', artists: [{ name: 'DJ Clei' }] },
      { name: 'Faz a Movimentação', artists: [{ name: 'DJ VL7' }] },
      { name: 'O Bueno é o Cacique x Vai Tomar Flechada', artists: [{ name: 'DJ Tchouzen' }] },
      { name: 'Ritmo Proibido', artists: [{ name: 'LeoZera' }] },
      { name: 'Sequência da Botação', artists: [{ name: 'DJ Ryder' }] },
      { name: 'Teu Preferido', artists: [{ name: 'DJ Brizy' }] },
      { name: 'Procedimento', artists: [{ name: 'DJ Alexia' }] },
      { name: 'O Puro Rock', artists: [{ name: 'DJ VL7' }] },
      { name: 'Insanidade na QBRD', artists: [{ name: 'Ruxell' }] },
      { name: 'Fode Quieta Mete Quieta', artists: [{ name: 'MC GW' }] },
      { name: 'Medley pras Novinhas', artists: [{ name: 'Christopher Luz' }] },
      { name: 'Bruxaria You Will See', artists: [{ name: 'DJ Cali' }] },
      { name: 'Perfume', artists: [{ name: 'DJ Alexia' }] },
      { name: 'Desande dos Mídias', artists: [{ name: 'DJ Sousa' }] },
      { name: 'Vai Senta Lá no Cinema', artists: [{ name: 'Morenin da 25' }] },
      { name: 'Quarto Escuro', artists: [{ name: 'MK no Beat' }] },
      { name: 'Montagem Homem do Ano', artists: [{ name: 'MC BN' }] },
      { name: 'Fiquei Triste', artists: [{ name: 'Maax Deejay' }] },
      { name: 'Amor de P', artists: [{ name: 'Bibi Babydoll' }] },
      { name: 'Montagem Oakley', artists: [{ name: 'DJ TS' }] },
      { name: 'Tipo Insta do Buzeira', artists: [{ name: 'Jhow' }] },
      { name: 'Depois do Vitrinni', artists: [{ name: 'DJ Tchouzen' }] },
      { name: 'Não Conta pra Ninguém', artists: [{ name: 'MC K.K' }] },
      { name: 'Na Onda da Bolha (Remix)', artists: [{ name: 'petrus.wav' }] },
      { name: 'Carlinhos é Rei Leão', artists: [{ name: 'DJ Tchouzen' }] },
      { name: 'Submundo das Cavalona', artists: [{ name: 'DJ Duarte' }] },
      { name: 'Zn dos Raul Bigode', artists: [{ name: 'yung mendes' }] },
      { name: 'Vai Senta pra Mim e pro Meu Parceiro', artists: [{ name: 'DJ Tchouzen' }] },
      { name: 'Deixa Eu Mandar Meu Passinho', artists: [{ name: 'DJ Aguilar' }] },
      { name: 'Corneta Soco no Tímpano', artists: [{ name: 'Megabaile do Areias' }, { name: 'MC Kitinho' }] },
      { name: 'Mandela Envolvente', artists: [{ name: 'DjNk7 O Ninja' }] },
      { name: 'Maloqueragem', artists: [{ name: 'DJ Waldeiyr' }] },
      { name: 'Isso é um Assalto', artists: [{ name: 'André Miquelotti' }] },
      { name: 'Quando Se Vai Perceber', artists: [{ name: 'DJ Tchouzen' }] },
      { name: '808 Me Aguarda', artists: [{ name: 'DJ Alexia' }] },
      { name: 'Automotivo Bruxaria Se Pedir Pra Eu Bater', artists: [{ name: 'MC K.K' }] },
      { name: 'Violino do Submundo', artists: [{ name: 'DJ Duarte' }] },
      { name: 'Orquestra Subverso', artists: [{ name: 'GP da ZL' }] },
      { name: 'Especial de Submundo Vol. 1', artists: [{ name: 'GP da ZL' }] },
      { name: 'Balança e Bafora', artists: [{ name: 'GP da ZL' }] },
      { name: 'Foda Selvagem', artists: [{ name: 'MC Nito' }] },
      { name: 'Menor do Ódio', artists: [{ name: 'DJ Ramon Sucesso' }] },
      { name: 'Rock Agressivo', artists: [{ name: 'DJ Alexia' }, { name: 'Ari Falcão' }, { name: 'HALC DJ' }], videoId: 'HyxTwMLIMf4' },
      { name: 'Mandelãoworld', artists: [{ name: 'DJ Blakes' }] },
      { name: 'Spooky 2', artists: [{ name: 'fennecxx' }] },
      { name: 'Maldição Egípcia do Lança', artists: [{ name: 'petrus.wav' }] },
      { name: 'Putaria é Só um Detalhe', artists: [{ name: 'DJ Cali' }] },
      { name: 'Novinha Eu Já Sei', artists: [{ name: 'DJ Alexia' }] },
      { name: 'Marreta do Chapolim', artists: [{ name: 'AG031' }] },
      { name: 'A Voz da Nova Geração', artists: [{ name: 'DJ LK da VB' }] },
      { name: 'Bebida Droga e Sexo', artists: [{ name: 'MC Neguinho do Morro' }] },
      { name: 'Não Nasci Pra Trabalhar Como CLT', artists: [{ name: 'cjnobeat' }] },
      { name: 'HARDMANDELA', artists: [{ name: 'DJ Mariachi' }] },
      { name: 'Rock do Submundo', artists: [{ name: 'DJ Alexia' }] },
      { name: 'Universo do Mandelão', artists: [{ name: 'DJ Blakes' }] },
      { name: 'Automotivo Embrazante', artists: [{ name: 'JC no Beat' }] },
      { name: 'Beat Sintético', artists: [{ name: 'GP da ZL' }] },
      { name: 'Surra de Vara', artists: [{ name: 'DJ LKS 067' }] },
      { name: 'Sessão de Travamento', artists: [{ name: 'GP da ZL' }] },
      { name: 'Beat Subverso', artists: [{ name: 'GP da ZL' }] },
      { name: 'Automotivo Bate Bate', artists: [{ name: 'Yuri Redicopa' }] },
      { name: 'Automotivo de Ladrão', artists: [{ name: 'DJ Patrick Muniz' }] },
      { name: 'Automotivo Paraliza Empina', artists: [{ name: 'MC K.K' }] },
      { name: 'Atabaque do Mal', artists: [{ name: 'HALC DJ' }] },
      { name: 'Bala Halls (Ela é Profissional 2)', artists: [{ name: 'GP da ZL' }] },
      { name: 'Automotivo Aurora Boreal', artists: [{ name: 'DJ NK3' }] },
      { name: 'Bruxaria Olha o Que Ela Faz', artists: [{ name: 'DJ LK da VB' }] },
      { name: 'Agudo Mágico 4', artists: [{ name: 'MC K.K' }] },
      { name: 'Botano (Útero Baixo)', artists: [{ name: 'DJ Caio Prince' }] },
      { name: 'Montagem Street Fighter das Sombras', artists: [{ name: 'DJ Kayo Original' }] },
      { name: 'Violino dos Drake', artists: [{ name: 'MC K.K' }] }
    ]
  },
  {
    id: 'special-gym-rock-workout-2026',
    name: 'GYM ROCK | WORKOUT 2026 💪🏻',
    cover: 'src/imagens/gym-rock-workout-2026.png',
    isSpecial: true,
    tracks: [
      { name: 'Highway to Hell', artists: [{ name: 'AC/DC' }] },
      { name: 'Back in Black', artists: [{ name: 'AC/DC' }] },
      { name: 'Thunderstruck', artists: [{ name: 'AC/DC' }] },
      { name: 'You Shook Me All Night Long', artists: [{ name: 'AC/DC' }] },
      { name: 'Paradise City', artists: [{ name: "Guns N’ Roses" }] },
      { name: 'Welcome to the Jungle', artists: [{ name: "Guns N’ Roses" }] },
      { name: 'Live and Let Die', artists: [{ name: "Guns N’ Roses" }] },
      { name: "Can’t Stop", artists: [{ name: 'Red Hot Chili Peppers' }] },
      { name: 'By the Way', artists: [{ name: 'Red Hot Chili Peppers' }] },
      { name: 'Dani California', artists: [{ name: 'Red Hot Chili Peppers' }] },
      { name: 'Give It Away', artists: [{ name: 'Red Hot Chili Peppers' }] },
      { name: 'Smells Like Teen Spirit', artists: [{ name: 'Nirvana' }] },
      { name: 'Enter Sandman', artists: [{ name: 'Metallica' }] },
      { name: 'Crazy Train', artists: [{ name: 'Ozzy Osbourne' }] },
      { name: 'Ace of Spades', artists: [{ name: 'Motörhead' }] },
      { name: 'Eye of the Tiger', artists: [{ name: 'Survivor' }] },
      { name: 'Mr. Brightside', artists: [{ name: 'The Killers' }] },
      { name: 'Somebody Told Me', artists: [{ name: 'The Killers' }] },
      { name: 'Sex on Fire', artists: [{ name: 'Kings of Leon' }] },
      { name: 'Seven Nation Army', artists: [{ name: 'The White Stripes' }] },
      { name: 'Blue Orchid', artists: [{ name: 'The White Stripes' }] },
      { name: 'Take Me Out', artists: [{ name: 'Franz Ferdinand' }] },
      { name: 'Song 2', artists: [{ name: 'Blur' }] },
      { name: 'American Idiot', artists: [{ name: 'Green Day' }] },
      { name: 'Holiday', artists: [{ name: 'Green Day' }] },
      { name: 'Know Your Enemy', artists: [{ name: 'Green Day' }] },
      { name: "The Kids Aren’t Alright", artists: [{ name: 'The Offspring' }] },
      { name: 'I Wanna Be Sedated', artists: [{ name: 'Ramones' }] },
      { name: 'Blitzkrieg Bop', artists: [{ name: 'Ramones' }] },
      { name: 'Black Betty', artists: [{ name: 'Ram Jam' }] },
      { name: 'We Will Rock You', artists: [{ name: 'Queen' }] },
      { name: 'More Than a Feeling', artists: [{ name: 'Boston' }] },
      { name: 'Rock You Like a Hurricane', artists: [{ name: 'Scorpions' }] },
      { name: "Livin’ on a Prayer", artists: [{ name: 'Bon Jovi' }] },
      { name: "It’s My Life", artists: [{ name: 'Bon Jovi' }] },
      { name: 'Rollin’ (Air Raid Vehicle)', artists: [{ name: 'Limp Bizkit' }] },
      { name: 'Bulls on Parade', artists: [{ name: 'Rage Against the Machine' }] },
      { name: 'Walk This Way', artists: [{ name: 'Aerosmith' }] },
      { name: 'Dream On', artists: [{ name: 'Aerosmith' }] },
      { name: 'Paint It, Black', artists: [{ name: 'The Rolling Stones' }] },
      { name: 'Paranoid', artists: [{ name: 'Black Sabbath' }] },
      { name: 'Sultans of Swing', artists: [{ name: 'Dire Straits' }] },
      { name: 'American Girl', artists: [{ name: 'Tom Petty and the Heartbreakers' }] },
      { name: 'Creep', artists: [{ name: 'Radiohead' }] },
      { name: 'Hysteria', artists: [{ name: 'Muse' }] },
      { name: 'Uprising', artists: [{ name: 'Muse' }] },
      { name: 'Do I Wanna Know?', artists: [{ name: 'Arctic Monkeys' }] },
      { name: 'Brianstorm', artists: [{ name: 'Arctic Monkeys' }] },
      { name: 'Tom Sawyer', artists: [{ name: 'Rush' }] },
      { name: 'Smooth Criminal', artists: [{ name: 'Alien Ant Farm' }] },
      { name: 'No One Knows', artists: [{ name: 'Queens of the Stone Age' }] },
      { name: 'Lonely Boy', artists: [{ name: 'The Black Keys' }] },
      { name: 'Woman', artists: [{ name: 'Wolfmother' }] },
      { name: 'Joker and the Thief', artists: [{ name: 'Wolfmother' }] },
      { name: 'Figure It Out', artists: [{ name: 'Royal Blood' }] },
      { name: 'Little Monster', artists: [{ name: 'Royal Blood' }] },
      { name: 'Highway Tune', artists: [{ name: 'Greta Van Fleet' }] },
      { name: 'Centuries', artists: [{ name: 'Fall Out Boy' }] },
      { name: 'Best of You', artists: [{ name: 'Foo Fighters' }] },
      { name: 'The Pretender', artists: [{ name: 'Foo Fighters' }] },
      { name: 'Learn to Fly', artists: [{ name: 'Foo Fighters' }] },
      { name: 'Monkey Wrench', artists: [{ name: 'Foo Fighters' }] },
      { name: 'Walk', artists: [{ name: 'Foo Fighters' }] },
      { name: 'In the End', artists: [{ name: 'Linkin Park' }] },
      { name: 'Numb', artists: [{ name: 'Linkin Park' }] },
      { name: 'The Emptiness Machine', artists: [{ name: 'Linkin Park' }] },
      { name: 'Two Faced', artists: [{ name: 'Linkin Park' }] },
      { name: 'Bring Me to Life', artists: [{ name: 'Evanescence' }] },
      { name: 'Feel Good Inc.', artists: [{ name: 'Gorillaz' }] },
      { name: 'American Bad Ass', artists: [{ name: 'Kid Rock' }] },
      { name: 'Are You Gonna Be My Girl', artists: [{ name: 'Jet' }] }
    ]
  },
  {
    id: 'special-funk-com-eletronica',
    name: 'FUNK COM ELETRÔNICA 😈',
    cover: 'src/imagens/funk-com-eletronica.png',
    isSpecial: true,
    tracks: [
      { name: 'Trinta e Oito (VIP Mix)', artists: [{ name: 'GIU' }] },
      { name: 'Vidrado', artists: [{ name: 'Zans' }] },
      { name: 'Push The Tempo', artists: [{ name: 'VOLAC' }] },
      { name: 'Oi Oi Oi', artists: [{ name: 'Dubdogz' }] },
      { name: 'Melhores Bailes do Mundo', artists: [{ name: 'Almanac' }] },
      { name: 'Cyclone', artists: [{ name: 'Almanac' }] },
      { name: 'Tira a Camisa', artists: [{ name: 'Almanac' }] },
      { name: 'I Can See', artists: [{ name: 'Javi Miramontes' }] },
      { name: 'Favela', artists: [{ name: 'Sielo' }] },
      { name: 'Talk', artists: [{ name: 'Chamo (AR)' }] },
      { name: 'Paranoia', artists: [{ name: 'Almanac' }] },
      { name: 'Doin Nottin', artists: [{ name: 'FatSync' }] },
      { name: 'Pike (Illusionize Remix)', artists: [{ name: 'Confesser' }] },
      { name: 'Step Back', artists: [{ name: 'Formalize' }] },
      { name: 'Tira a Roupa (Putaria Mix)', artists: [{ name: 'Beltran' }] },
      { name: 'Mister Type', artists: [{ name: 'FatSync' }] },
      { name: 'Soup', artists: [{ name: 'Byred' }] },
      { name: 'Your Mind', artists: [{ name: 'Zaark' }] },
      { name: 'Velocidade', artists: [{ name: 'Almanac' }] },
      { name: 'Top Down', artists: [{ name: 'Chamo (AR)' }] },
      { name: 'Naquele Pique', artists: [{ name: 'Gabe' }] },
      { name: 'Take Control', artists: [{ name: 'Ensek' }] },
      { name: 'Arms', artists: [{ name: 'Almanac' }] },
      { name: 'Oi Bum Bum', artists: [{ name: 'Smoothies' }] },
      { name: 'G Morning', artists: [{ name: 'Ishimaru' }] },
      { name: 'Baile in Braza', artists: [{ name: 'Freenzy Music' }] },
      { name: 'We Needed', artists: [{ name: 'Almanac' }] },
      { name: 'Vem Sentando', artists: [{ name: 'Society Haus' }] },
      { name: 'Granulator', artists: [{ name: 'Slow Sense' }] },
      { name: 'Tirando Tudo', artists: [{ name: 'LOPZ (BR)' }] },
      { name: 'Botadão', artists: [{ name: 'Ishimaru' }] },
      { name: 'Fighting', artists: [{ name: 'Almanac' }] },
      { name: 'Thick', artists: [{ name: 'Lemex' }] },
      { name: 'Pa Pa Pa (Vai)', artists: [{ name: 'Almanac' }] },
      { name: 'Boy', artists: [{ name: 'Gustavo Mota' }] },
      { name: 'Brazillionaire', artists: [{ name: 'Valentino Khan' }] },
      { name: 'Shake It', artists: [{ name: 'INNDRIVE' }] },
      { name: 'MarijuaNnNa', artists: [{ name: 'Almanac' }] },
      { name: 'Hoje', artists: [{ name: 'bewav' }] },
      { name: 'Trigger the Beat', artists: [{ name: 'DEFF (AR)' }] },
      { name: 'Vai Mulher', artists: [{ name: 'Society Haus' }] },
      { name: 'Mamacita', artists: [{ name: 'Gaddi' }] },
      { name: 'Mini Game', artists: [{ name: 'Almanac' }] },
      { name: 'Whip That Ass', artists: [{ name: 'Alan Oak' }] },
      { name: 'Balão', artists: [{ name: 'megatt' }] },
      { name: 'Loco', artists: [{ name: 'INNDRIVE' }] },
      { name: 'Macetadinha', artists: [{ name: 'Whighle' }] },
      { name: 'Super Bitch 2.0', artists: [{ name: 'Maxximal' }] },
      { name: 'Rap do Silva (Remix)', artists: [{ name: 'JØRD' }] },
      { name: 'Duhduhduh', artists: [{ name: 'Sage Armstrong' }] },
      { name: 'Embrazando', artists: [{ name: 'Dabi' }] },
      { name: 'Mexe Mexe', artists: [{ name: 'Gordo' }, { name: 'MC GW' }] },
      { name: 'Madame', artists: [{ name: 'BUJA (BR)' }] },
      { name: 'Só Percussão', artists: [{ name: 'Ishimaru' }] },
      { name: 'Ei Moto Táxi', artists: [{ name: 'Lucas Bahr' }] },
      { name: 'No Baile', artists: [{ name: 'Joaquin Lamanna' }] },
      { name: 'Noise', artists: [{ name: 'Almanac' }] },
      { name: 'Facilita', artists: [{ name: 'Fred again..' }] },
      { name: 'Hey (Na Na Na)', artists: [{ name: 'Almanac' }] },
      { name: 'Jazzy', artists: [{ name: 'FatSync' }] },
      { name: 'Em 4 Paredes', artists: [{ name: 'Breaking Beattz' }] },
      { name: 'Pleasure', artists: [{ name: 'Nikolas Kage' }] },
      { name: 'b0y', artists: [{ name: 'Marlon Zuck' }] },
      { name: 'Turugudatudu', artists: [{ name: 'Watzgood' }] },
      { name: 'Sensacional', artists: [{ name: 'Sico Vox' }] },
      { name: 'Cool', artists: [{ name: 'GIU' }] },
      { name: 'Ritmo do Papai', artists: [{ name: 'Koradize' }] },
      { name: 'Talkin', artists: [{ name: 'Pinco' }] },
      { name: 'Mete Bala', artists: [{ name: 'Slow Sense' }] },
      { name: 'I Don’t Know You', artists: [{ name: 'Kinhaa' }] },
      { name: 'Baile', artists: [{ name: 'VOLAC' }] },
      { name: 'Encosta Encosta', artists: [{ name: 'Lowderz' }] },
      { name: 'Pampa', artists: [{ name: 'Dubdisko' }] },
      { name: 'Baile da Roosevelt (Pam Pararam)', artists: [{ name: 'Koradize' }] },
      { name: 'Blow My Mind', artists: [{ name: 'Gustavo Mota' }] },
      { name: 'Mulher de Bandido', artists: [{ name: 'Low Disco' }] },
      { name: 'Girls and Boys', artists: [{ name: 'GIU' }] },
      { name: 'Carnavrau', artists: [{ name: 'Whighle' }, { name: 'MC GW' }] },
      { name: 'Trinta e Oito', artists: [{ name: 'GIU' }] },
      { name: 'What a Well', artists: [{ name: 'Burnout Crew' }] },
      { name: 'Baile Lotadão', artists: [{ name: 'Victor Lou' }] },
      { name: 'Teki Teki', artists: [{ name: 'Ishimaru' }] },
      { name: 'Baddest', artists: [{ name: 'Gaddi' }] },
      { name: 'Right', artists: [{ name: 'Gesus' }] },
      { name: 'Bonitinho', artists: [{ name: 'Berno' }] },
      { name: 'Girls Love Techno', artists: [{ name: 'Groove Delight' }] },
      { name: 'Journey', artists: [{ name: 'CastilhoMusic' }] },
      { name: 'Atrevida', artists: [{ name: 'Tommax' }] },
      { name: 'This', artists: [{ name: 'Sielo' }] },
      { name: 'Wait for It', artists: [{ name: 'Ricckbr' }] },
      { name: 'Dance', artists: [{ name: 'Zaark' }] },
      { name: 'Jaw', artists: [{ name: 'Ishimaru' }] }
    ]
  },
  {
    id: 'special-musicas-para-treinar-pesado',
    name: 'Músicas Para Treinar Pesado',
    cover: 'src/imagens/musicas-para-treinar-pesado.jpeg',
    isSpecial: true,
    tracks: [
      { name: 'No Batidão (Slowed)', artists: [{ name: 'ZXKAI' }] },
      { name: 'Mundo Fica (Slowed)', artists: [{ name: 'Pandemxnium' }] },
      { name: 'Los Voltaje', artists: [{ name: 'Sayfalse' }] },
      { name: 'Nunca Muda?', artists: [{ name: 'Scythermane' }] },
      { name: 'Sad About Funk', artists: [{ name: 'Kvnysh' }] },
      { name: 'Montagem Marreta', artists: [{ name: 'R9X' }] },
      { name: 'Parasite (Slowed)', artists: [{ name: 'Pandemxnium' }] },
      { name: 'MTG Pergunta', artists: [{ name: 'WXRTNAX' }] },
      { name: 'Montagem Para Nada', artists: [{ name: 'Sekimane' }] },
      { name: 'Flor Roxa', artists: [{ name: 'DJ Mimo Prod' }] },
      { name: 'Locked In!', artists: [{ name: 'Flame Runner' }] },
      { name: 'Funk Veneno (Super Slowed)', artists: [{ name: 'Flame Runner' }] },
      { name: 'Montagem Tentação', artists: [{ name: 'Dexhenry' }] },
      { name: 'Montagem Synoptica', artists: [{ name: 'WXRTNAX' }] },
      { name: 'Trajadão', artists: [{ name: 'WXRTNAX' }] },
      { name: 'Atento! (Slowed)', artists: [{ name: 'Leoseven' }] },
      { name: 'Fast Lane!', artists: [{ name: 'Flame Runner' }] },
      { name: 'Requiem for a Rave', artists: [{ name: 'TRYM' }] },
      { name: 'Tudo Mudo (Super Slowed)', artists: [{ name: 'Kverz' }] },
      { name: 'Dança no Bailão', artists: [{ name: 'Rushex' }] },
      { name: 'Quer Adrenalina', artists: [{ name: 'Avenxir' }] },
      { name: 'Gladiator', artists: [{ name: 'Sapfir Made It' }] },
      { name: 'Favela Chama', artists: [{ name: 'Rushex' }] },
      { name: 'Amor na Praia (Remix)', artists: [{ name: 'Flame Runner' }] },
      { name: 'Speak Up', artists: [{ name: 'Punxo' }] },
      { name: 'Always on My Mind', artists: [{ name: "Killin' Void" }] },
      { name: 'Do Relâmpago', artists: [{ name: 'Kverz' }] },
      { name: 'Rabeta Bass (Imanbek Remix)', artists: [{ name: 'KDDK' }] },
      { name: 'Pisada Solta', artists: [{ name: 'Rushex' }] },
      { name: 'Go Insane', artists: [{ name: 'D.O.H.' }] },
      { name: 'Montagem Hyperion', artists: [{ name: 'Naxzo on the Beat' }] },
      { name: 'Funk Luxo (Super Slowed)', artists: [{ name: 'TRXVELER' }] },
      { name: 'Speak Up (Slowed)', artists: [{ name: 'Punxo' }] },
      { name: 'Velvet Pain', artists: [{ name: 'Isolate.exe' }] },
      { name: 'Last Man Standing', artists: [{ name: 'Savas' }] },
      { name: 'Passo Bem Solto (Slowed)', artists: [{ name: 'ATLXS' }] },
      { name: 'Siete Jinetes', artists: [{ name: 'Scythermane' }] },
      { name: 'Astralyn (Slowed)', artists: [{ name: 'Hxntai Ninja' }] },
      { name: 'Espaço Liminal 2', artists: [{ name: 'NXGHT!' }] },
      { name: 'La Criminal', artists: [{ name: 'TRXSHBXY' }] },
      { name: 'Catalyst', artists: [{ name: 'ARXF' }] },
      { name: 'Brisa Morena', artists: [{ name: 'Flame Runner' }] },
      { name: 'Kick Your Neck', artists: [{ name: 'Polish Punisher' }] },
      { name: 'Vai o Chão', artists: [{ name: 'Kverz' }] },
      { name: 'A No Via (Ultra Slowed)', artists: [{ name: 'TRXVELER' }] },
      { name: 'Com Medo!', artists: [{ name: 'Sayfalse' }] },
      { name: 'Montagem Solar Atmosfera', artists: [{ name: 'Ariis' }] },
      { name: 'Montagem No Puedo', artists: [{ name: 'TRXSHBXY' }] },
      { name: 'Nephalem!', artists: [{ name: 'SHIPU' }] },
      { name: 'Emoções Mistas', artists: [{ name: 'Scythermane' }] },
      { name: 'Los Voltaje (Slowed)', artists: [{ name: 'Sayfalse' }] },
      { name: 'Noche Eterna', artists: [{ name: 'Flame Runner' }] },
      { name: 'Espaço Liminal', artists: [{ name: 'NXGHT!' }] },
      { name: 'Ecos do Abismo (Super Slowed)', artists: [{ name: 'Flame Runner' }] },
      { name: 'Toma Altura', artists: [{ name: 'ARXF' }] },
      { name: 'Funk Mi Camino', artists: [{ name: 'Sayfalse' }] },
      { name: 'Gros Teh', artists: [{ name: 'NØNAME' }] },
      { name: 'Esta Noche', artists: [{ name: 'TRXVELER' }] },
      { name: 'Hipnotize Me', artists: [{ name: 'Scythermane' }] },
      { name: 'Montagem Kawaii', artists: [{ name: 'ARXF' }] },
      { name: 'Deseo Ardiente', artists: [{ name: 'Flame Runner' }] },
      { name: 'Deadzone', artists: [{ name: 'Misfit' }] },
      { name: 'Luz da Terra', artists: [{ name: 'NXGHT!' }] },
      { name: 'Força Pesada', artists: [{ name: 'Sayfalse' }] },
      { name: 'Energia Oculta (Super Slowed)', artists: [{ name: 'Flame Runner' }] },
      { name: 'Rascal Funk', artists: [{ name: 'Krezus' }] },
      { name: 'Funk Paranormal', artists: [{ name: 'h6itam' }] },
      { name: 'Magnetar', artists: [{ name: 'DR MØB' }] },
      { name: 'Corrupção Funk', artists: [{ name: 'zxnc.' }] },
      { name: 'Titan! (Ultra Slowed)', artists: [{ name: 'GXMZ' }] },
      { name: 'As Chamas', artists: [{ name: 'Scythermane' }] },
      { name: 'Bufón!', artists: [{ name: 'Scythermane' }] },
      { name: 'Anarchy', artists: [{ name: 'Rogue Zero' }] },
      { name: 'Squid Game Funk (Super Slowed)', artists: [{ name: 'Lyke' }] },
      { name: 'Negócio Morto', artists: [{ name: 'Hugomasked' }] },
      { name: 'Montagem Cósmico Esmeralda 1.0', artists: [{ name: 'Seraphix' }] },
      { name: 'Deriva Malícia', artists: [{ name: '-Prey' }] },
      { name: 'Dreamcore Funk', artists: [{ name: 'DJ Arjey' }] },
      { name: 'Dança Bruxas', artists: [{ name: 'Scythermane' }] },
      { name: 'Uchi Machereca (Slowed)', artists: [{ name: 'gef7est' }] },
      { name: 'Estátua do Assassino', artists: [{ name: 'Raiden' }] },
      { name: 'Inferior', artists: [{ name: 'tawsogar' }] },
      { name: 'Untitled Funk', artists: [{ name: 'TRXSHBXY' }] },
      { name: 'Groovy!', artists: [{ name: 'Vermillion' }] },
      { name: 'Jogo de Tolos (Slowed)', artists: [{ name: 'Scythermane' }] },
      { name: 'Spooky (Slowed)', artists: [{ name: 'fennecxx' }] },
      { name: 'Slide de Tempestade (Slowed)', artists: [{ name: 'TRXVELER' }] },
      { name: 'X-Prime', artists: [{ name: 'DJ Samir' }] },
      { name: 'Montagem Winter Arc', artists: [{ name: 'DJ El Funk Testosterona' }] },
      { name: 'Jota Funk (Slowed)', artists: [{ name: 'Sayfalse' }] },
      { name: 'Mango Arc Funk', artists: [{ name: 'nikenmar' }] },
      { name: 'Luta de Cão', artists: [{ name: 'Scythermane' }] },
      { name: 'Sweet Summer Funk', artists: [{ name: 'MC Locked' }] }
    ]
  },
  {
    id: 'special-hardstyle-gym-2026',
    name: 'HARDSTYLE GYM 2026 🗿',
    cover: 'src/imagens/hardstyle-gym-2026.png',
    isSpecial: true,
    tracks: [
      { name: 'Telepathy', artists: [{ name: 'ist' }] },
      { name: 'Only Girl', artists: [{ name: 'puremind' }] },
      { name: 'Say It Right (Hardstyle)', artists: [{ name: 'BAKI' }] },
      { name: 'Angel of Darkness', artists: [{ name: 'Tooz' }] },
      { name: 'Disturbia (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Tourner Dans Le Vide (Hardstyle)', artists: [{ name: 'crypvolk' }] },
      { name: 'Bad Habits (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Animals (Hardstyle)', artists: [{ name: 'ist' }] },
      { name: 'Somebody That I Used To Know (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Play', artists: [{ name: 'Tooz' }] },
      { name: 'Weightless', artists: [{ name: 'Tooz' }] },
      { name: 'Drive By (Hardstyle)', artists: [{ name: 'TBMN' }] },
      { name: 'Adventure of a Lifetime (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Break Free', artists: [{ name: 'ist' }] },
      { name: 'Fire to the Rain (Hardstyle Remix)', artists: [{ name: 'Andonis' }] },
      { name: 'Shake It Up (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Atlantis (Hardstyle Cover)', artists: [{ name: 'ist' }] },
      { name: 'Fireflies (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Legend', artists: [{ name: 'Tevvez' }] },
      { name: 'I Kissed a Girl (Hardstyle)', artists: [{ name: 'TBMN' }] },
      { name: 'Chasing the Sun (Hardstyle)', artists: [{ name: 'Sick Legend' }] },
      { name: 'In Your Eyes (Hardstyle)', artists: [{ name: 'ist' }] },
      { name: 'Counting Stars (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Prayer in C (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'We Found Love (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'One More Time (Sped Up Edit)', artists: [{ name: 'Mqx' }] },
      { name: 'Halo', artists: [{ name: 'Always Mirin' }] },
      { name: 'Down (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'How Deep Is Your Love (Hardstyle Cover)', artists: [{ name: 'Tooz' }] },
      { name: 'All the Things She Said (Hardstyle Cover)', artists: [{ name: 'ist' }] },
      { name: 'Wrecking Ball (Hardstyle)', artists: [{ name: 'Tsenay' }] },
      { name: 'Deep In Your Love (Hardstyle)', artists: [{ name: 'ist' }] },
      { name: 'Summertime Sadness', artists: [{ name: 'Martin Bravi' }] },
      { name: 'Clarity', artists: [{ name: 'Jomarijan' }] },
      { name: 'Call Me Maybe (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Last Friday Night (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Bloody Mary (Hardstyle)', artists: [{ name: 'Enmity' }] },
      { name: 'Closer (Hardstyle Cover)', artists: [{ name: 'Tooz' }] },
      { name: 'Like a G6 (Hardstyle)', artists: [{ name: 'crypvolk' }] },
      { name: 'Paradise', artists: [{ name: 'Toneshifterz' }] },
      { name: 'Pompeii (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Rather Be (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Blame (Hardstyle – Sped Up)', artists: [{ name: 'Mr. Glass' }] },
      { name: 'As It Was (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'S&M (Hardstyle)', artists: [{ name: 'Poseidon' }] },
      { name: 'Lights', artists: [{ name: 'Hardstyle Cvnt' }] },
      { name: 'Locked Out of Heaven (Hardstyle – Sped Up)', artists: [{ name: 'BAKI' }] },
      { name: 'I Ain’t Worried (Hardstyle)', artists: [{ name: 'Poseidon' }] },
      { name: 'She’s All I Wanna Be (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Too Sweet (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Crazy What Love Can Do (Hardstyle)', artists: [{ name: 'ist' }] },
      { name: 'Miss You (Remix)', artists: [{ name: 'Oliver Tree' }] },
      { name: 'You Make Me Feel… (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Somewhere Only We Know (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Insomnia (Hardstyle)', artists: [{ name: 'ist' }] },
      { name: 'Celestial (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Pon de Replay (Hardstyle Remix)', artists: [{ name: 'Kratos' }] },
      { name: 'Really Don’t Care (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Beggin’ (Hardstyle Remix)', artists: [{ name: 'Tooz' }] },
      { name: 'Mojabi Ghost (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Firework', artists: [{ name: 'Always Mirin' }] },
      { name: 'Rolling in the Deep (Hardstyle)', artists: [{ name: 'Sick Legend' }] },
      { name: 'Don’t Let Me Down (Hardwell & Sephyx Remix)', artists: [{ name: 'The Chainsmokers' }] },
      { name: 'The Pump', artists: [{ name: 'TR3NVHN' }] },
      { name: 'The Nights (Hardstyle Edit)', artists: [{ name: 'Thymo' }] },
      { name: 'Break Your Heart (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'My Soldiers Rage', artists: [{ name: 'Maul' }] },
      { name: 'Cry for You (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'My Rival (Hardstyle)', artists: [{ name: 'MYSK' }] },
      { name: 'Just Let Me', artists: [{ name: 'Tooz' }] },
      { name: 'Make You Mine (Hardstyle)', artists: [{ name: 'ist' }] },
      { name: 'I Just Died in Your Arms', artists: [{ name: 'Pxlish Beatz' }] },
      { name: 'Mr. Saxobeat', artists: [{ name: 'Martin Bravi' }] },
      { name: 'Never Let You Go', artists: [{ name: 'vxcelm' }] },
      { name: 'My Happy Ending (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: '405 Anthem', artists: [{ name: 'Mqx' }] },
      { name: 'Gettin’ Over You', artists: [{ name: 'Tooz' }] },
      { name: 'The One That Got Away (Hardstyle)', artists: [{ name: 'Poseidon' }] },
      { name: 'Blah Blah Blah (Zany Remix)', artists: [{ name: 'Armin van Buuren' }] },
      { name: 'Part of Me (Hardstyle)', artists: [{ name: 'Sick Legend' }] },
      { name: 'More (Hardstyle)', artists: [{ name: 'Tooz' }] },
      { name: 'Another Love (Hardstyle Cover)', artists: [{ name: 'Tooz' }] }
    ]
  },
  {
    id: 'special-funk-brasileiro-2026',
    name: 'FUNK BRASILEIRO 2026 🇧🇷 MAIORES HITS 🔥',
    cover: 'src/imagens/FUNK BRASILEIRO 2026 🇧🇷 MAIORES HITS 🔥 .jpeg',
    isSpecial: true,
    tracks: [
      { name: 'Posso Até Não Te Dar Flores', artists: [{ name: 'DJ Japa NK' }] },
      { name: 'Famosinha', artists: [{ name: 'DJ Caio Vieira' }] },
      { name: 'Sequência Feiticeira', artists: [{ name: 'Pedro Sampaio' }] },
      { name: 'Jetski', artists: [{ name: 'Pedro Sampaio' }] },
      { name: 'Gostosin', artists: [{ name: 'Anitta' }] },
      { name: 'Faz Assim', artists: [{ name: 'Gabby B' }] },
      { name: 'Golpe Baixo', artists: [{ name: 'Leo Marques' }] },
      { name: 'Set do Japa NK 2.0', artists: [{ name: 'DJ Japa NK' }] },
      { name: 'Me Postou no Daily (Festa do Big G)', artists: [{ name: 'MC GP' }] },
      { name: 'Montagem Câmera Lenta', artists: [{ name: 'DJ Duarte' }] },
      { name: 'Vai Seu Gostoso', artists: [{ name: 'Manu Dal Santo' }] },
      { name: 'Amo Minha Favela', artists: [{ name: 'DJ Japa NK' }] },
      { name: 'Bota', artists: [{ name: 'Ludmilla' }] },
      { name: 'I Love Favela', artists: [{ name: 'DJ Marcela Biondo' }] },
      { name: 'Descer', artists: [{ name: 'Kew' }] },
      { name: 'MTG na Imaginação (Topo Sessions Vol. 1)', artists: [{ name: 'DJ Topo' }] },
      { name: 'Passei de Gol', artists: [{ name: 'Leo Marques' }] },
      { name: 'Fui Mlk', artists: [{ name: 'Nilo' }] },
      { name: 'Tipo Nino vs Kabrinha', artists: [{ name: 'DJ Biel Divulga' }] },
      { name: 'Oh Garota Eu Quero Você Só Pra Mim', artists: [{ name: 'Oruam' }] },
      { name: 'Na Cama do MS', artists: [{ name: 'Miguel Santos' }] },
      { name: 'Pirocada Quente', artists: [{ name: 'MC Jvila' }] },
      { name: 'Instinto Animal', artists: [{ name: 'Manu Dal Santo' }] },
      { name: 'Olha Pra Cara de Quem Te…', artists: [{ name: 'MC Luuky' }] },
      { name: 'Dia D', artists: [{ name: 'Leo Marques' }] },
      { name: 'Encosta na Parede', artists: [{ name: 'MC Pedrinho' }] },
      { name: 'Bundinha', artists: [{ name: 'Gabby B' }] },
      { name: 'A Danada Me Ligando', artists: [{ name: 'MC Cebezinho' }] },
      { name: 'Ato', artists: [{ name: 'MC Pacheco' }] },
      { name: '365 Dias (Vida Mansa)', artists: [{ name: 'MC Marks' }] },
      { name: 'Construção de Amor', artists: [{ name: 'DJ CZ' }] },
      { name: 'Puta É Só um Detalhe', artists: [{ name: 'DJ Douglinhas' }] },
      { name: 'Penélope Charmosa 2', artists: [{ name: 'Boladin 211' }] },
      { name: 'Barbie', artists: [{ name: 'MC Tuto' }] },
      { name: 'Sei Que Tu Me Odeia', artists: [{ name: 'Anitta' }] },
      { name: 'Rebolando', artists: [{ name: 'Kew' }] },
      { name: 'Tá Rico os Menino do Gueto 🍀', artists: [{ name: 'MC IG' }] },
      { name: 'Motinha 2.0 (Mete Marcha)', artists: [{ name: 'Dennis' }] },
      { name: 'Se Essa Bunda For Uma Empresa', artists: [{ name: 'Chefin' }] },
      { name: 'Thainá Thainá', artists: [{ name: 'MC Nito' }] },
      { name: 'Automotivo da Turbulência', artists: [{ name: 'MC Oliver' }] },
      { name: 'Sequência Striptease', artists: [{ name: 'Pedro Sampaio' }] },
      { name: 'The Box Medley Funk 2', artists: [{ name: 'The Box' }] },
      { name: 'Malvadinho', artists: [{ name: 'MC Luuky' }] },
      { name: 'Fala na Cara', artists: [{ name: 'MC Paiva ZS' }] },
      { name: 'Menina de Vermelho', artists: [{ name: 'MC Menor JP' }] },
      { name: 'Bunda 🍑', artists: [{ name: 'Emilia' }] },
      { name: 'MTG Quem Não Quer Sou Eu', artists: [{ name: 'DJ Topo' }] },
      { name: 'Vai Tomando Pock Pock', artists: [{ name: 'MC Lele JP' }] },
      { name: '300 no 7', artists: [{ name: 'MC GP' }] },
      { name: 'Tá OK', artists: [{ name: 'Dennis' }] },
      { name: 'Puta Mexicana', artists: [{ name: 'DJ Jeeh FDC' }] },
      { name: 'Tropa do Mestre', artists: [{ name: 'Menino GS' }] },
      { name: 'Vai Malandra', artists: [{ name: 'Anitta' }] },
      { name: 'Bumbum Granada', artists: [{ name: 'MC Zaac' }] },
      { name: 'Medley de Igaratá 3', artists: [{ name: 'MC Negão Original' }] },
      { name: 'Aquariano Nato', artists: [{ name: 'MC Saci' }] },
      { name: 'Dançarina', artists: [{ name: 'Pedro Sampaio' }] },
      { name: 'Evoluiu', artists: [{ name: 'MC Kevin O Chris' }] },
      { name: 'Faz um Vuk Vuk', artists: [{ name: 'MC Kevin O Chris' }] },
      { name: 'Baile do Panta', artists: [{ name: 'Nego Trufa' }] },
      { name: 'Senta e Cala a Boca', artists: [{ name: 'cjnobeat' }] },
      { name: 'Te Maceto Depois do Baile', artists: [{ name: 'DJ Zigão' }] },
      { name: 'Bate Volta', artists: [{ name: 'DJ Topo' }] },
      { name: 'Ensaio das Maravilhas', artists: [{ name: 'Pedro Sampaio' }] },
      { name: 'PocPoc', artists: [{ name: 'Pedro Sampaio' }] },
      { name: 'MTG Quero Te Encontrar', artists: [{ name: 'DJ JZ' }] },
      { name: 'Dia de Fluxo', artists: [{ name: 'AgroPlay' }] },
      { name: 'Vermelho', artists: [{ name: 'Gloria Groove' }] },
      { name: 'Perversa', artists: [{ name: 'Pedro Sampaio' }] },
      { name: 'Baby Eu Tava na Rua da Água', artists: [{ name: 'TR' }] },
      { name: 'Até o Sol Raiar', artists: [{ name: 'MC Hariel' }] },
      { name: 'MTG Quero Ver Se Você Tem Atitude', artists: [{ name: 'DJ Luan Gomes' }] },
      { name: 'Não Fosse Tão Tarde (MTG Remix)', artists: [{ name: 'Lou Garcia' }] },
      { name: 'Dança Pra Me Provocar', artists: [{ name: 'DJ João Pereira' }] },
      { name: 'A Dona Aranha', artists: [{ name: 'Luísa Sonza' }] },
      { name: 'Sequência Colocadão', artists: [{ name: 'Pedro Sampaio' }] },
      { name: 'Alegría', artists: [{ name: 'Tiago PZK' }] },
      { name: 'Savage Funk', artists: [{ name: 'Anitta' }] },
      { name: 'Recadin no Espelho', artists: [{ name: 'Luísa Sonza' }] },
      { name: 'Depois do Baile', artists: [{ name: 'Dennis' }] },
      { name: 'Playboy Bunny', artists: [{ name: 'Gabby B' }] },
      { name: 'Sentar pro Trem', artists: [{ name: 'DJ KN de Vila Velha' }] },
      { name: 'Rolé na Favela de Nave', artists: [{ name: 'Oruam' }] },
      { name: 'Deixa o Cavalo Correr', artists: [{ name: 'Oldilla' }] },
      { name: 'Bota um Funk', artists: [{ name: 'Pedro Sampaio' }] },
      { name: 'Bate', artists: [{ name: 'Dennis' }] },
      { name: 'Funk Rave', artists: [{ name: 'Anitta' }] },
      { name: 'MTG Tropicana', artists: [{ name: 'DJ Luan Gomes' }] },
      { name: 'Fama', artists: [{ name: 'Pedro Sampaio' }] },
      { name: 'Joga Pra Lua', artists: [{ name: 'Anitta' }] },
      { name: 'Chama Ela', artists: [{ name: 'Lexa' }, { name: 'Pedro Sampaio' }] },
      { name: 'MTG Stereo Love', artists: [{ name: 'cjnobeat' }] },
      { name: 'Machuquei', artists: [{ name: 'MC Guizinho Niazi' }] },
      { name: 'Os Menino Tá Com o Pacote', artists: [{ name: 'MC PH' }] },
      { name: 'Bum Bum Tam Tam', artists: [{ name: 'MC Fioti' }] },
      { name: 'Olha a Explosão', artists: [{ name: 'MC Kevinho' }] },
      { name: 'Mostra Seu Talento', artists: [{ name: 'MC Jacaré' }] }
    ]
  },
  {
    id: 'special-submundo-808',
    name: 'Submundo 808',
    cover: 'src/imagens/submundo_808_cover.png',
    isSpecial: true,
    tracks: [
      { name: 'Submundo 808', artists: [{ name: 'DJ NG Original' }] },
      { name: 'PEPECA NERVOSA (VERSÃO SUBMUNDO)', artists: [{ name: 'GP da ZL' }, { name: 'MC Jhey' }] },
      { name: 'SOCA SOCA DO SUBMUNDO (Funk Version)', artists: [{ name: 'DJ GBR' }, { name: 'Victor Lou' }, { name: 'MC Theuzyn' }] },
      { name: 'Puta É Só Um Detalhe', artists: [{ name: 'DJ Cali' }] },
      { name: 'Achei Que Era Pagode X Mete Bala', artists: [{ name: 'DJ Léo da 17' }] },
      { name: 'O Baile', artists: [{ name: 'MC Meduza' }, { name: 'DJ Day do Carmo' }, { name: 'DJ Gordinho da VF' }] },
      { name: 'Baile da Disney7', artists: [{ name: 'DJ Mandrake' }] },
      { name: 'Discute com IA', artists: [{ name: 'DJ CZ' }] },
      { name: 'São Paulo (Remix)', artists: [{ name: 'DJ Guss' }] },
      { name: 'Bem-Vinda ao Submundo', artists: [{ name: 'GP da ZL' }] },
      { name: 'Fiu Fiu das Novinha Bdo', artists: [{ name: 'MC Zkw' }] },
      { name: 'Na Onda da Bolha', artists: [{ name: 'Petrus.wav' }] },
      { name: 'Pode Vim Pode Vim', artists: [{ name: 'DJ CR Original' }] },
      { name: 'Na Favelinha', artists: [{ name: 'MC Mari' }] },
      { name: 'Cyclonado Submundo', artists: [{ name: 'DJ Mariachi' }] },
      { name: 'Submundo Bailão', artists: [{ name: 'DJ Clei' }] },
      { name: 'Bruxaria das Famosinhas', artists: [{ name: 'DJ LL' }] },
      { name: 'Senta', artists: [{ name: 'DJ John Saucer' }] },
      { name: 'Not Like Us Bolha', artists: [{ name: 'Hanai' }] },
      { name: 'Espancamente', artists: [{ name: 'DJ Folh4' }] },
      { name: 'Perigosamente', artists: [{ name: 'GP da ZL' }] },
      { name: 'Romance É Romance vs Hoje Eu Quero Trair', artists: [{ name: 'Leozinn No Beat' }] },
      { name: 'Bruxaria You Will See', artists: [{ name: 'DJ Cali' }] },
      { name: 'Mimosa 8000', artists: [{ name: 'Hanai' }, { name: 'Costa' }] },
      { name: 'Trampolim (feat. MC Dudu)', artists: [{ name: 'Megabaile do Areias' }] },
      { name: 'MTG Agressiva', artists: [{ name: 'Don Dali' }] },
      { name: 'Fogo no Parquinho', artists: [{ name: 'Megabaile do Areias' }] },
      { name: 'Oakley Oakley Oakley', artists: [{ name: 'DJ LL' }] },
      { name: 'Vem pro Cabaré Agressivo', artists: [{ name: 'DJ Holanda' }] },
      { name: 'Submundo RJ', artists: [{ name: 'DJ Folh4' }] },
      { name: 'Hard RJ', artists: [{ name: 'DJ Pedro Neves' }] },
      { name: 'Corneta Soco no Tímpano', artists: [{ name: 'Megabaile do Areias' }, { name: 'MC Kitinho' }] },
      { name: 'Penetrada Agressiva', artists: [{ name: 'Leozinn No Beat' }] },
      { name: 'Isso Aqui Ñ É MCMB', artists: [{ name: 'Novin Yarp' }] },
      { name: 'Tuf Tuf Pof Pof', artists: [{ name: 'DJ Mariachi' }] },
      { name: 'Ritual das Maconheiras', artists: [{ name: 'HALC DJ' }] },
      { name: 'Fode que Thriller', artists: [{ name: 'GP da ZL' }] },
      { name: 'Toma Piru dos Neurose', artists: [{ name: 'DJ Cali' }] },
      { name: 'Barulho do Rock 2', artists: [{ name: 'DJ Turin' }] },
      { name: 'Fritando Muito, Carburando Mais Ainda', artists: [{ name: 'DJ Fanqui' }] },
      { name: 'Boca de Pelo', artists: [{ name: 'DJ Blakes' }] },
      { name: 'Pokpok', artists: [{ name: 'Adame DJ' }] },
      { name: 'Tuin Destrói Paredão 2.0', artists: [{ name: 'MC Bin Laden' }] },
      { name: 'Fica de 4', artists: [{ name: 'DJ LL' }] },
      { name: 'Beat Psicodélico', artists: [{ name: 'DJ Blakes' }] },
      { name: 'Ultra Turn Down', artists: [{ name: 'DJ Japão' }] },
      { name: 'Lets Go', artists: [{ name: 'DJ Blakes' }] },
      { name: 'Abusadamente (Submundo)', artists: [{ name: 'DJ Alexia' }] },
      { name: 'Na Onda do Mega', artists: [{ name: 'HALC DJ' }] },
      { name: 'Move Your Feet vs Pente Pente', artists: [{ name: 'DJ Jeeh FDC' }] },
      { name: 'Ritmo da 011', artists: [{ name: 'DJ Chrisl' }] },
      { name: 'Chama Novinha', artists: [{ name: 'DJ Japão' }] },
      { name: 'Beat Fodelância Glacial', artists: [{ name: 'DJ Rafinha Duarte' }] },
      { name: 'O Último Tuin (Faixa Bônus)', artists: [{ name: 'DJ KS 011' }] },
      { name: 'Conflito', artists: [{ name: 'Adame DJ' }] },
      { name: 'Techno 2', artists: [{ name: 'Adame DJ' }] },
      { name: 'Automotivo Gritante', artists: [{ name: 'DJ PL Mandrake03' }] },
      { name: 'Sequência de Macetação', artists: [{ name: 'DJ Anderson Silva' }] },
      { name: 'Hardmandela', artists: [{ name: 'DJ Mariachi' }] },
      { name: 'Beco de Trás', artists: [{ name: 'DJ Mariachi' }] },
      { name: 'O Baile Vai Começar', artists: [{ name: 'DJ LL' }] },
      { name: 'Montagem Baile de Favela', artists: [{ name: 'MC RN Original' }] },
      { name: 'Atura ou Surta', artists: [{ name: 'DJ Kley' }] },
      { name: '2026', artists: [{ name: 'Jhow' }] },
      { name: 'Hoje Eu Vou para Sub Sim', artists: [{ name: 'HALC DJ' }] },
      { name: 'Terror Oriental', artists: [{ name: 'MC Lan' }] },
      { name: 'Passinho do Revólver x Bota o Dedo pro Alto', artists: [{ name: 'DJ Blakes' }] },
      { name: 'Rock', artists: [{ name: 'Moura DJ' }] },
      { name: 'Putaria Pras Mulher', artists: [{ name: 'DJ LL' }] },
      { name: 'Bebida de Bandido', artists: [{ name: 'DJ Ianco' }] },
      { name: 'Pupila Dilata', artists: [{ name: 'MC LCKaiique' }] },
      { name: 'Pega o Beatzin', artists: [{ name: 'DJ Alexia' }] },
      { name: 'Bruxaria do Naldo', artists: [{ name: 'DJ Keevin' }] },
      { name: 'Orquestra Diabólica da Escuridão Profunda', artists: [{ name: 'DJ Fanqui' }] },
      { name: 'Ritmo Psicótico', artists: [{ name: 'DJ Mariachi' }] },
      { name: 'Bem-vinda ao Submundo (Remix)', artists: [{ name: 'GP da ZL' }] },
      { name: 'Submundo Espacial', artists: [{ name: 'DJ Holanda' }] },
      { name: 'Tamborzada do Submundo', artists: [{ name: 'HALC DJ' }] },
      { name: 'Rock Agressivo', artists: [{ name: 'DJ Alexia' }, { name: 'Ari Falcão' }, { name: 'HALC DJ' }], videoId: 'HyxTwMLIMf4' },
      { name: 'Automotivo Místico 2', artists: [{ name: 'DJ Blakes' }] },
      { name: 'Ritmo das Trevas', artists: [{ name: 'DJ Pablo RB' }] },
      { name: 'Cocaine Funk', artists: [{ name: 'DJ Blakes' }] },
      { name: 'Destruição Caótica', artists: [{ name: 'DJ Souza Beat' }] },
      { name: 'Mega Agressividade Sonora', artists: [{ name: 'DJ Nathan RV' }] }
    ]
  },
];
